services:
  # Main bot service - runs login.js with health check
  - type: web
    name: biarfca-bot
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20.11.0
    # Health check endpoint
    healthCheckPath: /health

